
/**
 * Image URL: C:\\Users\\nthom\\OneDrive\\Documents\\NetBeansProjects\\LogCalculatorV2\\nbproject\\images\\beach-1845945_1920.jpg
 * @author Nathan Thomas
 * @version 1.0
 */
public class AdvancedCalcForm extends javax.swing.JFrame {

   /**
    * Creates new form AdvancedCalcForm
    */
   public AdvancedCalcForm() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      WelcomeLabel = new javax.swing.JLabel();
      jLabel1 = new javax.swing.JLabel();
      timeIn1 = new javax.swing.JTextField();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      timeIn2 = new javax.swing.JTextField();
      jLabel4 = new javax.swing.JLabel();
      timeOut1 = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      timeIn3 = new javax.swing.JTextField();
      timeOut3 = new javax.swing.JTextField();
      CalculateTimeButton = new javax.swing.JButton();
      calculatedTimeLabel = new javax.swing.JLabel();
      timeOut2 = new javax.swing.JTextField();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jMenuBar1 = new javax.swing.JMenuBar();
      jMenu1 = new javax.swing.JMenu();
      PTMenu = new javax.swing.JMenu();
      OTMenu = new javax.swing.JMenu();
      SLPMenu = new javax.swing.JMenu();

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
      setBackground(new java.awt.Color(204, 204, 204));
      setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
      setIconImages(null);
      setMinimumSize(new java.awt.Dimension(500, 500));
      setSize(new java.awt.Dimension(500, 700));
      getContentPane().setLayout(null);

      WelcomeLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
      WelcomeLabel.setForeground(new java.awt.Color(255, 255, 51));
      WelcomeLabel.setText("Welcome, ");
      getContentPane().add(WelcomeLabel);
      WelcomeLabel.setBounds(20, 10, 290, 24);

      jLabel1.setForeground(new java.awt.Color(255, 255, 51));
      jLabel1.setText("Clock-In");
      getContentPane().add(jLabel1);
      jLabel1.setBounds(22, 52, 60, 30);

      timeIn1.setBackground(new java.awt.Color(255, 204, 102));
      getContentPane().add(timeIn1);
      timeIn1.setBounds(80, 50, 60, 30);

      jLabel2.setForeground(new java.awt.Color(255, 255, 51));
      jLabel2.setText("Clock-Out");
      getContentPane().add(jLabel2);
      jLabel2.setBounds(160, 50, 70, 30);

      jLabel3.setForeground(new java.awt.Color(255, 255, 51));
      jLabel3.setText("Clock-In");
      getContentPane().add(jLabel3);
      jLabel3.setBounds(20, 90, 60, 30);

      timeIn2.setBackground(new java.awt.Color(255, 204, 102));
      getContentPane().add(timeIn2);
      timeIn2.setBounds(80, 90, 60, 30);

      jLabel4.setForeground(new java.awt.Color(255, 255, 51));
      jLabel4.setText("Clock-Out");
      getContentPane().add(jLabel4);
      jLabel4.setBounds(160, 90, 70, 30);

      timeOut1.setBackground(new java.awt.Color(255, 204, 102));
      getContentPane().add(timeOut1);
      timeOut1.setBounds(230, 50, 60, 30);

      jLabel5.setForeground(new java.awt.Color(255, 255, 51));
      jLabel5.setText("Clock-In");
      getContentPane().add(jLabel5);
      jLabel5.setBounds(20, 130, 60, 30);

      jLabel6.setForeground(new java.awt.Color(255, 255, 51));
      jLabel6.setText("Clock-Out");
      getContentPane().add(jLabel6);
      jLabel6.setBounds(160, 130, 70, 30);

      timeIn3.setBackground(new java.awt.Color(255, 204, 102));
      timeIn3.setText("0");
      getContentPane().add(timeIn3);
      timeIn3.setBounds(80, 130, 60, 30);

      timeOut3.setBackground(new java.awt.Color(255, 204, 102));
      timeOut3.setText("0");
      getContentPane().add(timeOut3);
      timeOut3.setBounds(230, 130, 60, 30);

      CalculateTimeButton.setBackground(new java.awt.Color(102, 204, 255));
      CalculateTimeButton.setText("Calculate");
      CalculateTimeButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            CalculateTimeButtonActionPerformed(evt);
         }
      });
      getContentPane().add(CalculateTimeButton);
      CalculateTimeButton.setBounds(20, 180, 87, 26);

      calculatedTimeLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
      calculatedTimeLabel.setForeground(new java.awt.Color(255, 255, 255));
      calculatedTimeLabel.setText("Log Time:");
      getContentPane().add(calculatedTimeLabel);
      calculatedTimeLabel.setBounds(127, 177, 350, 30);

      timeOut2.setBackground(new java.awt.Color(255, 204, 102));
      getContentPane().add(timeOut2);
      timeOut2.setBounds(230, 90, 60, 30);

      jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
      jLabel7.setForeground(new java.awt.Color(255, 255, 255));
      jLabel7.setText("Instructions:");
      getContentPane().add(jLabel7);
      jLabel7.setBounds(20, 240, 100, 30);

      jLabel8.setForeground(new java.awt.Color(255, 255, 255));
      jLabel8.setText("Input time as three or four digits  (ex., \"0800\" or \"430\")");
      getContentPane().add(jLabel8);
      jLabel8.setBounds(22, 266, 309, 16);

      jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
      jLabel9.setForeground(new java.awt.Color(255, 255, 51));
      jLabel9.setText("PUT A ZERO (\"0\") IN ANY CLOCK IN/OUT FIELD NOT USED!");
      getContentPane().add(jLabel9);
      jLabel9.setBounds(22, 288, 440, 19);

      jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\nthom\\OneDrive\\Documents\\NetBeansProjects\\LogCalculatorV2\\nbproject\\images\\beach-1845945_1920.jpg"));
      getContentPane().add(jLabel10);
      jLabel10.setBounds(0, 0, 570, 510);

      jMenu1.setText("Select User");

      PTMenu.setText("PT");
      jMenu1.add(PTMenu);

      OTMenu.setText("OT");
      jMenu1.add(OTMenu);

      SLPMenu.setText("SLP");
      jMenu1.add(SLPMenu);

      jMenuBar1.add(jMenu1);

      setJMenuBar(jMenuBar1);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void CalculateTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateTimeButtonActionPerformed
      int invalidValueCount = 0;
      int firstClockIn = Integer.parseInt(timeIn1.getText());
      int secondClockIn = Integer.parseInt(timeIn2.getText());
      int thirdClockIn = Integer.parseInt(timeIn3.getText());
      int firstClockOut = Integer.parseInt(timeOut1.getText());
      int secondClockOut = Integer.parseInt(timeOut2.getText());
      int thirdClockOut = Integer.parseInt(timeOut3.getText());
      int firstMinutes = 0;
      int secondMinutes = 0;
      int thirdMinutes = 0;
      int totalHours = 0;
      int totalMinutes = 0;
      
      // Convert to Military Time values
      if (firstClockOut < firstClockIn) {
         firstClockOut += 1200;
      }
      if (secondClockOut < secondClockIn) {
         secondClockOut += 1200;
      }
      if (thirdClockOut < thirdClockIn) {
         thirdClockOut += 1200;
      }
      
      // verify input times are valid
      invalidValueCount += checkValues(firstClockIn);
      invalidValueCount += checkValues(firstClockOut);
      invalidValueCount += checkValues(secondClockIn);
      invalidValueCount += checkValues(secondClockOut);
      invalidValueCount += checkValues(thirdClockIn);
      invalidValueCount += checkValues(thirdClockOut);
      
      // Convert raw time values to minutes
      firstMinutes = calculateMinutes(firstClockIn, firstClockOut);
      secondMinutes = calculateMinutes(secondClockIn, secondClockOut);
      thirdMinutes = calculateMinutes(thirdClockIn, thirdClockOut);

      totalMinutes = firstMinutes + secondMinutes + thirdMinutes;
      
      while (totalMinutes >= 60) {
         totalMinutes -= 60;
         totalHours += 1;
      }
      
      if (invalidValueCount == 0) {
         calculatedTimeLabel.setText("Log Time: " + totalHours + " hours, "
                 + totalMinutes + " minutes");
      } else {
         calculatedTimeLabel.setText("ERROR! " + invalidValueCount
                 + " time values are invalid.");
      }
   }//GEN-LAST:event_CalculateTimeButtonActionPerformed

   private int checkValues(int time) {
      int isValid = 0;
      
      if (time % 100 >= 60) {
         isValid = 1;
      } else if (time > 2359) {
         isValid = 1;
      }
      
      return isValid;
   }
   
   private int calculateMinutes(int clockIn, int clockOut) {
      int hoursInMinutes = ((clockOut / 100) - (clockIn / 100)) * 60;
      int firstMinutes = clockIn % 100;
      int secondMinutes = clockOut % 100;
      int totalMinutes = 0;
      
      totalMinutes = hoursInMinutes - firstMinutes + secondMinutes;
      
      return totalMinutes;
   }
      
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(AdvancedCalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(AdvancedCalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(AdvancedCalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(AdvancedCalcForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new AdvancedCalcForm().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton CalculateTimeButton;
   private javax.swing.JMenu OTMenu;
   private javax.swing.JMenu PTMenu;
   private javax.swing.JMenu SLPMenu;
   private javax.swing.JLabel WelcomeLabel;
   private javax.swing.JLabel calculatedTimeLabel;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JMenu jMenu1;
   private javax.swing.JMenuBar jMenuBar1;
   private javax.swing.JTextField timeIn1;
   private javax.swing.JTextField timeIn2;
   private javax.swing.JTextField timeIn3;
   private javax.swing.JTextField timeOut1;
   private javax.swing.JTextField timeOut2;
   private javax.swing.JTextField timeOut3;
   // End of variables declaration//GEN-END:variables
}
